default_prefix = "a-"
prefix_override = "<"
wsi_url = "http://127.0.0.1:3030"
wsi_auth = "sex"

[database]
  host = "161.97.104.129"
  username = "assyst"
  password = "150baea3da60388a09d1c4fbcaf058c4"
  database = "assyst"
  port = 63985