bot_id = 571661221854707713
bot_list_port = 3801
disable_bad_translator = true
disable_reminder_check = true

[auth]
annmarie = "madtoken1234"
bot_list_webhook = "ac50f712c11963be00bde2372acd92e7"
discord_bot_list_post_stats = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0IjoxLCJpZCI6IjU3MTY2MTIyMTg1NDcwNzcxMyIsImlhdCI6MTYzNzU0NTgxN30.wm82i1Eapc_9ICJ1i6HJD3PD1b3Q6tjv1FOm9KulHmI"
maryjane = "MjMzNjY3NDQ4ODg3MzEyMzg1.YKFhWw.VGcXJIr0DyRaUyBxVr174H7xQTXP4uJsbNnA4dpxHjY"
patreon = "Bearer -BHFi_CxGYCFLzlZQd3sPWGF2ejf7sJtVz6G1LsFamY"
top_gg_post_stats = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU3MTY2MTIyMTg1NDcwNzcxMyIsImJvdCI6dHJ1ZSwiaWF0IjoxNjI3ODk4Njk3fQ.YKHpYMVdt-DedQ6OilKEeIAXtotO4JGV-Gdq8Ie79UA"
discords_post_stats = "a10b4cb01ac5c8ba4b93a10ea346666e8e74adbf14d71982a959433557bd4a37171c4ad3fd9ce30de70b11678187eb93720229452095b6deb417ccf695311fa3"
wsi = "0192837465"                                                                                                                                                                   #"sex"                                                                                                                                                                          #[ "sex" ]
lottie_render = "ass"
rapidapi = "9e26b961c5msh346b4b5ebc61105p1a5cdbjsn7d24ab7ae662"
codesprint = ""
cdn = "0192837465"
discord = "NTcxNjYxMjIxODU0NzA3NzEz.XMQ_AA.eq2aAXVqCDocqWp5jJ3hoZ--GAM"#"Njc0MzY3NjYwNzEyMTMyNjA4.GL34uT.RwAl9eU_r4fPryLwKoDRVpXaak04052OZea2dw"

[database]
host = "65.108.47.241"
username = "assyst"
password = "150baea3da60388a09d1c4fbcaf058c4"
database = "assyst"
port = 63985

[logs]
fatal = ""
info = ""
vote = ""
panic_notify_role = 0

[prefix]
default = "-"
override = "~#~"

[url]
annmarie = "http://164.68.109.4:23443"
maryjane = "https://discard.cc/api/v0"
wsi = "127.0.0.1:3030"                       #[ "" "65.108.47.241:30331" ]
lottie_render = "ass"
rule34 = "http://164.68.109.4:61167/search"
codesprint = ""
cdn = "https://cdn.jacher.io"
proxy = "http://proxy.y21_.repl.co/"
eval = ""
wombo = "http://65.108.47.241:6765/generate"

[user]
admins = [
  312715611413413889,
  302394290368151553,
  144856004771708929,
  233667448887312385,
] #233667448887312385
blacklist = []
